# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0emessages.proto"*\n\tJoinLobby\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07lobbyId\x18\x02 \x01(\x05"(\n\x08JoinGame\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\x05" \n\x10RequestLobbyList\x12\x0c\n\x04user\x18\x01 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "messages_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_JOINLOBBY"]._serialized_start = 18
    _globals["_JOINLOBBY"]._serialized_end = 60
    _globals["_JOINGAME"]._serialized_start = 62
    _globals["_JOINGAME"]._serialized_end = 102
    _globals["_REQUESTLOBBYLIST"]._serialized_start = 104
    _globals["_REQUESTLOBBYLIST"]._serialized_end = 136
# @@protoc_insertion_point(module_scope)
